import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import { useAuth } from '../../auth/AuthContext';
import { AuthLayout } from '../../layouts/AuthLayout';
import type { RegisterInput } from '../../services/domain/auth';

const specializations = ['Toán', 'Ngữ Văn', 'Tiếng Anh', 'Khoa học tự nhiên - Công nghệ', 'Lịch sử - Địa lí', 'Giáo dục công dân', 'Nghệ thuật - Giáo dục thể chất', 'Văn phòng'] as const;
const schema = z.object({
  name: z.string().trim().min(1, 'Nhập họ và tên').max(120), username: z.string().trim().min(3, 'Username tối thiểu 3 ký tự').max(80).regex(/^[A-Za-z0-9._-]+$/, 'Username chỉ gồm chữ, số, dấu chấm, gạch ngang hoặc gạch dưới'), email: z.string().email('Email không hợp lệ').optional().or(z.literal('')), password: z.string().min(8, 'Mật khẩu tối thiểu 8 ký tự'), confirmPassword: z.string(), role: z.enum(['STUDENT', 'TEACHER']), className: z.string().optional(), specialization: z.string().optional(), gender: z.enum(['', 'Nam', 'Nữ']).optional(),
}).superRefine((value, ctx) => { if (value.password !== value.confirmPassword) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['confirmPassword'], message: 'Mật khẩu xác nhận không khớp' }); if (value.role === 'STUDENT' && !/^[6-9]A[0-9]+$/.test(value.className || '')) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['className'], message: 'Lớp theo định dạng 6A1 đến 9A...' }); if (value.role === 'TEACHER' && !value.specialization) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['specialization'], message: 'Chọn tổ chuyên môn' }); });
type FormValue = z.infer<typeof schema>;

export function RegisterPage() {
  const { user, register: registerAccount } = useAuth(); const navigate = useNavigate();
  const { register, watch, setValue, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<FormValue>({ resolver: zodResolver(schema), defaultValues: { role: 'STUDENT', gender: '' } });
  const role = watch('role');
  useEffect(() => { if (role === 'STUDENT') setValue('specialization', ''); else setValue('className', ''); }, [role, setValue]);
  if (user) return <Navigate to="/bang-tin" replace />;
  const onSubmit = async (value: FormValue) => { try { const payload: RegisterInput = { ...value, email: value.email || null, gender: value.gender || null, className: value.role === 'STUDENT' ? value.className : null, specialization: value.role === 'TEACHER' ? value.specialization : null }; await registerAccount(payload); navigate('/bang-tin'); } catch (error: unknown) { const response = (error as { response?: { data?: { error?: { field?: string; message?: string } } } }).response?.data?.error; if (response?.field) setError(response.field as keyof FormValue, { message: response.message }); else toast.error(response?.message || 'Không thể tạo tài khoản. Vui lòng thử lại.'); } };
  return <AuthLayout><form className="register-card" onSubmit={handleSubmit(onSubmit)}><Link className="auth-back" to="/"><ArrowLeft size={15} /> VỀ TRANG CHỦ</Link><div className="wordmark">VIVIORA</div><span className="eyebrow">CHƯƠNG ĐẦU TIÊN CỦA BẠN</span><h1>ĐĂNG KÝ</h1><p className="register-intro">Tạo tài khoản để bắt đầu đọc, chia sẻ và mở khóa hành trình riêng.</p><div className="register-grid"><label>HỌ VÀ TÊN<input autoComplete="name" {...register('name')} />{errors.name && <small className="error">{errors.name.message}</small>}</label><label>USERNAME<input autoComplete="username" {...register('username')} />{errors.username && <small className="error">{errors.username.message}</small>}</label><label className="register-wide">EMAIL <span className="optional">TÙY CHỌN</span><input type="email" autoComplete="email" {...register('email')} />{errors.email && <small className="error">{errors.email.message}</small>}</label><div className="register-wide"><span className="register-label">BẠN LÀ</span><div className="role-switch"><button type="button" className={role === 'STUDENT' ? 'selected' : ''} onClick={() => setValue('role', 'STUDENT')}>HỌC SINH</button><button type="button" className={role === 'TEACHER' ? 'selected' : ''} onClick={() => setValue('role', 'TEACHER')}>GIÁO VIÊN</button></div></div>{role === 'STUDENT' ? <label>LỚP<input placeholder="Ví dụ: 8A1" {...register('className')} />{errors.className && <small className="error">{errors.className.message}</small>}</label> : <label>TỔ CHUYÊN MÔN<select {...register('specialization')}><option value="">Chọn tổ chuyên môn</option>{specializations.map((item) => <option value={item} key={item}>{item}</option>)}</select>{errors.specialization && <small className="error">{errors.specialization.message}</small>}</label>}<label>GIỚI TÍNH <span className="optional">TÙY CHỌN</span><select {...register('gender')}><option value="">Chưa cập nhật</option><option value="Nam">Nam</option><option value="Nữ">Nữ</option></select></label><label>MẬT KHẨU<input type="password" autoComplete="new-password" {...register('password')} />{errors.password && <small className="error">{errors.password.message}</small>}</label><label>XÁC NHẬN MẬT KHẨU<input type="password" autoComplete="new-password" {...register('confirmPassword')} />{errors.confirmPassword && <small className="error">{errors.confirmPassword.message}</small>}</label></div><button className="button primary register-submit" disabled={isSubmitting}>{isSubmitting ? 'ĐANG TẠO...' : 'TẠO TÀI KHOẢN'} <ArrowRight size={17} /></button><p className="auth-switch">Đã có tài khoản? <Link to="/dang-nhap">ĐĂNG NHẬP</Link></p></form></AuthLayout>;
}
