import { keepPreviousData, useQuery, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import { ArrowLeft, Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import toast from 'react-hot-toast';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { adminUsersApi, type ManagedUserInput } from '../../services/domain/adminUsers';
import { MemberFormModal } from '../../components/members/MemberFormModal';
import { ConfirmMemberDeleteModal } from '../../components/members/ConfirmMemberDeleteModal';
import type { ManagedUser } from '../../types/models';
import { UserAvatar } from '../../components/common/UserAvatar';
import { formatDate } from '../../utils/dateTime';

export function AdminMemberDetailPage() {
  const { userId = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const [editing, setEditing] = useState(false); const [deleting, setDeleting] = useState(false); const [busy, setBusy] = useState(false); const query = useQuery({ queryKey: ['admin-member', userId], queryFn: () => adminUsersApi.get(userId).then((response) => response.data.data), enabled: Boolean(userId), placeholderData: keepPreviousData });
  if (query.isPending && !query.data) return <div className="state-card">Đang tải thành viên...</div>; if (query.isError || !query.data) return <div className="state-card error">Không tìm thấy thành viên.</div>;
  const user = query.data as ManagedUser; const save = async (data: ManagedUserInput) => { await adminUsersApi.update(user.id, data); toast.success('Đã cập nhật thành viên'); setEditing(false); await client.invalidateQueries({ queryKey: ['admin-member', userId] }); await client.invalidateQueries({ queryKey: ['admin-members'] }); }; const remove = async () => { setBusy(true); try { await adminUsersApi.remove(user.id); toast.success('Đã xóa thành viên'); navigate('/quan-tri/thanh-vien'); } catch (error: unknown) { const message = axios.isAxiosError(error) ? error.response?.data?.error?.message : undefined; toast.error(message || 'Không thể xóa thành viên.'); } finally { setBusy(false); setDeleting(false); } };
  return <div className="member-detail-page"><Link className="back-link" to="/quan-tri/thanh-vien"><ArrowLeft size={17} /> QUAY LẠI DANH SÁCH</Link><section className="member-detail-page-card"><div className="member-detail-page-header"><div><span className="eyebrow">CHI TIẾT THÀNH VIÊN</span><h1>{user.name}</h1><p>@{user.username}</p></div><div className="admin-row-actions"><button className="button secondary" type="button" onClick={() => setEditing(true)}><Pencil size={17} /> CHỈNH SỬA</button><button className="button danger" type="button" onClick={() => setDeleting(true)}><Trash2 size={17} /> XÓA</button></div></div><div className="member-detail-hero"><UserAvatar name={user.name} avatarUrl={user.avatar_url} size="large" /><div><span className={`member-role-badge member-role-${user.role.toLowerCase()}`}>{user.role === 'ADMIN' ? 'ADMIN' : user.role === 'TEACHER' ? 'GIÁO VIÊN' : 'HỌC SINH'}</span><h2>{user.name}</h2><p>{user.email || 'Chưa cập nhật email'}</p></div></div><dl className="member-detail-facts"><div><dt>USERNAME</dt><dd>{user.username}</dd></div><div><dt>TRẠNG THÁI</dt><dd><span className={`member-status ${user.is_active ? 'active' : 'inactive'}`}>{user.is_active ? 'Đang hoạt động' : 'Đã vô hiệu hóa'}</span></dd></div><div><dt>GIỚI TÍNH</dt><dd>{user.gender || 'Chưa cập nhật'}</dd></div><div><dt>NGÀY TẠO</dt><dd>{formatDate(user.created_at)}</dd></div>{user.role === 'STUDENT' && <div><dt>LỚP</dt><dd>{user.class_name || 'Chưa cập nhật'}</dd></div>}{user.role === 'TEACHER' && <div><dt>TỔ CHUYÊN MÔN</dt><dd>{user.specialization || 'Chưa cập nhật'}</dd></div>}</dl></section>{editing && <MemberFormModal user={user} onClose={() => setEditing(false)} onSubmit={save} />}{deleting && <ConfirmMemberDeleteModal user={user} loading={busy} onClose={() => setDeleting(false)} onConfirm={() => void remove()} />}</div>;
}
